/**
 * Generate the structural half of the SDK from the frozen AUDR schema.
 *
 * Usage: node scripts/gen-schema.ts [--check]
 *
 * Writes two files, neither edited by hand:
 *   src/generated-validator.ts  the schema compiled by Ajv into standalone code, so Ajv stays
 *                               a development dependency and nothing is compiled at run time;
 *   src/generated-schema.ts     the record types, rendered by quicktype, and the supported
 *                               release.
 *
 * Which AUDR error code each schema failure reports is decided in `src/validate.ts`. With
 * `--check`, nothing is written and the exit status says whether the files on disk are current.
 */
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

import { Ajv2020 } from 'ajv/dist/2020.js';
import standalone from 'ajv/dist/standalone/index.js';
import { format, resolveConfig } from 'prettier';
import { FetchingJSONSchemaStore, InputData, JSONSchemaInput, quicktype } from 'quicktype-core';

const ROOT = join(import.meta.dirname, '..');
const SCHEMA = join(ROOT, '../../../spec/audr.schema.json');
const VALIDATOR_OUT = join(ROOT, 'src/generated-validator.ts');
const SCHEMA_OUT = join(ROOT, 'src/generated-schema.ts');
const HEADER = '// GENERATED by scripts/gen-schema.ts from spec/audr.schema.json. DO NOT EDIT.';

const RECORD_TYPE = 'AudrRecordShape';
/** Exported type names by record path, given to quicktype as each schema's `title`. */
const TYPE_NAMES: Readonly<Record<string, string>> = {
  '': RECORD_TYPE,
  '/emitter': 'Emitter',
  '/emitter/component': 'EmitterComponent',
  '/timing': 'Timing',
  '/resource': 'Resource',
  '/resource/type': 'ResourceType',
  '/resource/operation': 'Operation',
  '/resource/modality': 'Modality',
  '/run': 'Run',
  '/run/run_type': 'RunType',
  '/run/outcome': 'RunOutcome',
  '/attribution': 'Attribution',
  '/attribution/environment': 'Environment',
  '/usage': 'Usage',
  '/usage/llm': 'LlmUsage',
  '/usage/tool': 'ToolUsage',
  '/cost': 'Cost',
  '/cost/llm': 'LlmCost',
  '/cost/tool': 'ToolCost',
};

const ANNOTATIONS = new Set(['$comment', 'title', 'description', 'examples']);

type Node = Readonly<Record<string, unknown>>;

function isNode(value: unknown): value is Node {
  return typeof value === 'object' && value !== null && !Array.isArray(value);
}

function asNode(value: unknown, where: string): Node {
  if (!isNode(value)) throw new Error(`expected a schema object at ${where}`);
  return value;
}

// ---------------------------------------------------------------------------------------
// Validator.

function validatorSource(schema: Node): string {
  const ajv = new Ajv2020({
    allErrors: true,
    // Attach each failing keyword's schema, which `validate.ts` reads to name the failure.
    verbose: true,
    // NaN and Infinity are not JSON numbers.
    strictNumbers: true,
    // `format` is not asserted; `pattern` and the prose rules in `validate.ts` cover it.
    validateFormats: false,
    // `then` branches name properties and requirements the enclosing object declares.
    strictRequired: false,
    strictTypes: false,
    messages: false,
    code: { source: true, esm: true },
  });
  const code = standalone.default(ajv, ajv.compile(schema));
  const exported = /^"use strict";export const validate = (\w+);export default \1;/.exec(code);
  if (!exported) throw new Error('unexpected Ajv standalone preamble');
  const body = code
    .slice(exported[0].length)
    .replaceAll('require("ajv/dist/runtime/ucs2length").default', 'codePoints');
  if (/\brequire\(|\bimport\b/.test(body)) throw new Error('generated validator imports code');
  const validate = exported[1] ?? '';
  return `// @ts-nocheck
${HEADER}
import type { SchemaError } from './validate.js';

${body}

/** A string's length in code points, as JSON Schema counts it; a lone surrogate is one. */
function codePoints(value) {
  return [...value].length;
}

/** Every rule of the schema that \`data\` breaks, in the order Ajv finds them. */
export function schemaErrors(data: unknown): readonly SchemaError[] {
  return ${validate}(data) ? [] : ${validate}.errors;
}
`;
}

// ---------------------------------------------------------------------------------------
// Types.

interface ExtensionSlot {
  /** The record path of the object that admits the extension properties. */
  readonly path: string;
  readonly pattern: string;
  /** The schema every extension property's value must meet. */
  readonly value: Node;
}

/** Every `patternProperties` pattern in the schema. quicktype drops them. */
function extensionSlots(node: Node, path = ''): ExtensionSlot[] {
  const own = Object.entries(isNode(node.patternProperties) ? node.patternProperties : {}).map(
    ([pattern, value]) => ({ path, pattern, value: asNode(value, `${path}/${pattern}`) }),
  );
  const nested = Object.entries(isNode(node.properties) ? node.properties : {}).flatMap(
    ([key, child]) => extensionSlots(asNode(child, `${path}/${key}`), `${path}/${key}`),
  );
  return [...own, ...nested];
}

/** The literal prefix every extension pattern starts with, such as `x_`. */
function extensionPrefix(schema: Node): string {
  const prefixes = new Set(
    extensionSlots(schema).map(({ path, pattern }) => {
      const prefix = /^\^([a-z0-9_]+)\[/.exec(pattern)?.[1];
      if (prefix === undefined) {
        throw new Error(`no TypeScript key type for the pattern ${pattern} at ${path}`);
      }
      return prefix;
    }),
  );
  const [prefix, ...others] = prefixes;
  if (prefix === undefined || others.length > 0) {
    throw new Error(`expected one extension prefix, found ${[...prefixes].join(', ') || 'none'}`);
  }
  return prefix;
}

/** A copy of the schema whose named objects and enums carry their type name as `title`. */
function titled(schema: Node): Record<string, unknown> {
  const copy = structuredClone(schema) as Record<string, unknown>;
  for (const [path, name] of Object.entries(TYPE_NAMES)) {
    const target = path
      .split('/')
      .slice(1)
      .reduce<Node>((node, key) => asNode(asNode(node.properties, path)[key], path), copy);
    (target as Record<string, unknown>).title = name;
  }
  return copy;
}

async function recordTypes(schema: Node): Promise<string> {
  const input = new JSONSchemaInput(new FetchingJSONSchemaStore());
  await input.addSource({ name: RECORD_TYPE, schema: JSON.stringify(titled(schema)) });
  const inputData = new InputData();
  inputData.addInput(input);
  const { lines } = await quicktype({
    inputData,
    lang: 'typescript',
    // A timestamp stays the RFC 3339 string it is on the wire.
    inferDateTimes: false,
    rendererOptions: { 'just-types': 'true', readonly: 'true', 'prefer-unknown': 'true' },
  });
  const source = lines
    .join('\n')
    // quicktype's `readonly` stops at the member, so a map's entries stay writable.
    .replace(/\{ \[key: string\]: (\w+) \}/g, 'Readonly<Record<string, $1>>')
    // Under `exactOptionalPropertyTypes`, an optional property must also accept `undefined`.
    .replace(/^(\s*readonly \w+\?: )(.+);$/gm, '$1$2 | undefined;');
  checkMembers(source);
  const missing = Object.values(TYPE_NAMES).filter(
    (name) => !new RegExp(`^export (interface|type) ${name}\\b`, 'm').test(source),
  );
  if (missing.length > 0) throw new Error(`quicktype did not emit ${missing.join(', ')}`);
  return extensionSlots(schema).reduce(withExtensionSlot, source);
}

/**
 * Fail when quicktype's output no longer has the shape the rewrites above expect, rather than
 * let a rewrite silently match nothing: every member readonly, every optional member also
 * accepting `undefined`, and every map converted.
 */
function checkMembers(source: string): void {
  const members = source.split('\n').filter((line) => /^\s+(readonly )?\w+\??:/.test(line));
  const wrong = members.filter(
    (line) =>
      !line.trimStart().startsWith('readonly ') ||
      (/^\s*readonly \w+\?:/.test(line) && !line.endsWith(' | undefined;')),
  );
  if (source.includes('[key: string]')) wrong.push('a map left as an index signature');
  if (wrong.length > 0) {
    throw new Error(`unexpected quicktype output:\n  ${wrong.map((l) => l.trim()).join('\n  ')}`);
  }
}

/** `source` with the index signature for `slot` closing its object's interface. */
function withExtensionSlot(source: string, { path, value }: ExtensionSlot): string {
  const name = TYPE_NAMES[path];
  if (name === undefined) throw new Error(`no type name for the extension slot at ${path}`);
  const types = ([] as unknown[]).concat(value.type);
  if (!types.every((type) => type === 'integer' || type === 'number')) {
    throw new Error(`no TypeScript type for the extension properties at ${path}`);
  }
  const body = new RegExp(`(^export interface ${name} \\{\\n[\\s\\S]*?)(^\\})`, 'm');
  if (!body.test(source)) throw new Error(`quicktype did not emit ${name} as an interface`);
  const doc =
    typeof value.description === 'string'
      ? `/** ${value.description.replaceAll('*/', '*\\/')} */\n`
      : '';
  const signature = `${doc}readonly [key: ExtensionKey]: number | undefined;\n`;
  return source.replace(body, (_, members: string, close: string) => members + signature + close);
}

async function schemaSource(schema: Node): Promise<string> {
  const id = String(schema.$id);
  const release = /\/v(\d+\.\d+\.\d+)\//.exec(id)?.[1];
  if (release === undefined) throw new Error(`no release in the schema $id ${id}`);
  const version = asNode(asNode(schema.properties, '#/properties').spec_version, 'spec_version');
  const prefix = extensionPrefix(schema);
  return `${HEADER}

/** The AUDR release this package implements, from the schema's \`$id\`. */
export const SPEC_VERSION = ${JSON.stringify(release)};
/** Every \`spec_version\` the schema admits. */
export const SUPPORTED_SPEC_VERSION = ${new RegExp(String(version.pattern)).toString()};

/** An \`${prefix}*\` provider or implementation counter. */
export type ExtensionKey = \`${prefix}\${string}\`;

${await recordTypes(schema)}
`;
}

// ---------------------------------------------------------------------------------------
// Output.

async function formatted(source: string, file: string): Promise<string> {
  return format(source, { ...(await resolveConfig(file)), filepath: file });
}

const text = readFileSync(SCHEMA, 'utf8');
const schema = asNode(JSON.parse(text), SCHEMA);
// The validator embeds the schema it compiles, so it gets one without prose. A property
// named after an annotation is a schema object, and stays.
const bare = asNode(
  JSON.parse(text, (key, value: unknown) =>
    (ANNOTATIONS.has(key) || key.startsWith('x_')) && !isNode(value) ? undefined : value,
  ),
  SCHEMA,
);

const outputs: [string, string][] = [
  [VALIDATOR_OUT, await formatted(validatorSource(bare), VALIDATOR_OUT)],
  [SCHEMA_OUT, await formatted(await schemaSource(schema), SCHEMA_OUT)],
];

if (process.argv.includes('--check')) {
  const stale = outputs.filter(
    ([file, output]) => !existsSync(file) || readFileSync(file, 'utf8') !== output,
  );
  for (const [file] of stale) console.error(`  ${file} is stale; run \`make schema\``);
  process.exitCode = stale.length > 0 ? 1 : 0;
  if (stale.length === 0) console.log('  generated schema files are current');
} else {
  for (const [file, output] of outputs) writeFileSync(file, output);
  console.log(`  wrote ${outputs.map(([file]) => file.slice(ROOT.length + 1)).join(', ')}`);
}
