"""Generate src/audr/record/_schema.py from the frozen AUDR schema.

Usage: python scripts/gen_models.py [--check]

Pre-processing of an in-memory copy of the schema (the file under spec/ is never modified):
  * titles are injected so nested objects get stable class names;
  * `pattern` is removed from date-time properties (pydantic cannot apply a regex to a datetime;
    AwareDatetime plus the millisecond rule in _validate.py cover it);
  * `patternProperties` is removed from the three extensible blocks (ExtensibleBase enforces x_*),
    otherwise the generator collapses them to plain dicts.
Post-processing removes the per-class `model_config` blocks so the base classes' config applies.
"""

from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
import tempfile
from collections.abc import Callable
from pathlib import Path
from typing import Any

HERE = Path(__file__).resolve().parent
SCHEMA = HERE.parents[3] / "spec" / "audr.schema.json"
OUT = HERE.parent / "src" / "audr" / "record" / "_schema.py"
TITLES = {
    "/properties/emitter": "Emitter",
    "/properties/timing": "Timing",
    "/properties/resource": "Resource",
    "/properties/run": "Run",
    "/properties/attribution": "Attribution",
    "/properties/usage": "Usage",
    "/properties/usage/properties/llm": "LlmUsage",
    "/properties/usage/properties/tool": "ToolUsage",
    "/properties/cost": "Cost",
    "/properties/cost/properties/llm": "LlmCost",
    "/properties/cost/properties/tool": "ToolCost",
}
EXTENSIBLE = {"LlmUsage", "ToolUsage", "ToolCost"}
BASE = "audr.record._base.FrozenBase"
EXT_BASE = "audr.record._base.ExtensibleBase"
HEADER = (
    "# GENERATED by scripts/gen_models.py from spec/audr.schema.json. DO NOT EDIT.\n"
    "# ruff: noqa\n# fmt: off\n# mypy: ignore-errors"
)
CONFIG_BLOCK = re.compile(r'\n    model_config = ConfigDict\(\n        extra="forbid",\n    \)\n')


def _walk(node: object, path: str, fn: Callable[[dict[str, Any], str], None]) -> None:
    if isinstance(node, dict):
        fn(node, path)
        for key, value in node.items():
            _walk(value, f"{path}/{key}", fn)
    elif isinstance(node, list):
        for i, value in enumerate(node):
            _walk(value, f"{path}/{i}", fn)


def prepare(schema: dict[str, Any]) -> dict[str, Any]:
    def fn(node: dict[str, Any], path: str) -> None:
        if path in TITLES:
            node["title"] = TITLES[path]
        if node.get("format") == "date-time":
            node.pop("pattern", None)
        if node.get("title") in EXTENSIBLE:
            node.pop("patternProperties", None)

    _walk(schema, "", fn)
    schema["title"] = "AUDR"
    return schema


def generate() -> str:
    schema = prepare(json.loads(SCHEMA.read_text()))
    with tempfile.TemporaryDirectory() as td:
        tmp_schema = Path(td) / "audr.schema.json"
        tmp_schema.write_text(json.dumps(schema))
        bases = Path(td) / "bases.json"
        bases.write_text(json.dumps({n: EXT_BASE for n in EXTENSIBLE}))
        out = Path(td) / "_schema.py"
        subprocess.run(
            [
                sys.executable,
                "-m",
                "datamodel_code_generator",
                "--input",
                str(tmp_schema),
                "--input-file-type",
                "jsonschema",
                "--output",
                str(out),
                "--output-model-type",
                "pydantic_v2.BaseModel",
                "--class-name",
                "AUDR",
                "--use-title-as-name",
                "--base-class",
                BASE,
                "--base-class-map",
                str(bases),
                "--enum-field-as-literal",
                "all",
                "--use-annotated",
                "--field-constraints",
                "--use-schema-description",
                "--collapse-root-models",
                "--target-python-version",
                "3.11",
                "--disable-timestamp",
                "--use-double-quotes",
                "--formatters",
                "ruff-format",
                "--custom-file-header",
                HEADER,
            ],
            check=True,
        )
        text = out.read_text()
    text = CONFIG_BLOCK.sub("\n", text)
    text = text.replace(
        "from pydantic import AwareDatetime, ConfigDict, Field, constr",
        "from pydantic import AwareDatetime, Field, constr",
    )
    return text


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    text = generate()
    if args.check:
        if OUT.read_text() != text:
            print(f"{OUT} is stale; run `make models`", file=sys.stderr)
            return 1
        print("generated model is up to date")
        return 0
    OUT.write_text(text)
    print(f"wrote {OUT} ({len(text.splitlines())} lines)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
