# GENERATED by scripts/gen_models.py from spec/audr.schema.json. DO NOT EDIT.
# ruff: noqa
# fmt: off
# mypy: ignore-errors

from __future__ import annotations

from typing import Annotated, Literal
from pydantic import AwareDatetime, Field, constr
from audr.record._base import ExtensibleBase, FrozenBase
from typing_extensions import TypeAliasType


class Emitter(FrozenBase):
    """
    Identifies the software component that wrote the record.
    """

    component: Annotated[
        Literal["harness", "router", "provider"],
        Field(
            description="Component that wrote the record. This field identifies the caller that metered tool usage and cost."
        ),
    ]
    name: Annotated[
        str,
        Field(
            description="Package identifier for the emitter.",
            examples=["@audr/openrouter"],
            min_length=1,
        ),
    ]
    version: Annotated[
        str,
        Field(
            description="Emitter release used to attribute data-quality issues.",
            examples=["0.5.1"],
            min_length=1,
        ),
    ]


class Timing(FrozenBase):
    """
    Event completion, ingest, and duration observations.
    """

    event_time: Annotated[
        AwareDatetime,
        Field(
            description="Event invocation time in RFC 3339 format with millisecond precision; for streams, use stream termination."
        ),
    ]
    received_time: Annotated[
        AwareDatetime | None,
        Field(
            description="Ingest time in RFC 3339 format with millisecond precision. Set by the sink."
        ),
    ] = None
    duration_ms: Annotated[
        int | None, Field(description="Event execution duration in milliseconds.", ge=0)
    ] = None


class Resource(FrozenBase):
    """
    Identifies the consumed model or tool. Model operations require type=model; tool_execution and retrieval require type=tool.
    """

    provider: Annotated[
        str,
        Field(
            description="Canonical lowercase provider slug. For tool operations, identify the executing vendor or platform; use self-hosted for locally run tools.",
            examples=[
                "anthropic",
                "openai",
                "google",
                "aws-bedrock",
                "azure-openai",
                "self-hosted",
            ],
            pattern="^[a-z0-9-]+$",
        ),
    ]
    type: Annotated[
        Literal["model", "tool"],
        Field(
            description="Named resource kind: model for model operations or tool for tool_execution and retrieval. resource.operation selects the usage block."
        ),
    ]
    name: Annotated[
        str,
        Field(
            description="Verbatim provider model identifier for models, or stable logical tool/backend identifier for tools. Do not normalize model names or use URLs and versioned function symbols for tools.",
            examples=[
                "claude-sonnet-4-20250514",
                "search_tickets",
                "run_sql",
                "web_search",
            ],
            min_length=1,
        ),
    ]
    operation: Annotated[
        Literal["generation", "embedding", "reranking", "tool_execution", "retrieval"],
        Field(
            description="Operation class that selects resource.type and usage: model operations use model with usage.llm; tool_execution and retrieval use tool with usage.tool."
        ),
    ]
    modality: Annotated[
        Literal["text", "image", "audio", "multimodal"] | None,
        Field(
            description="The modality of the task or operation. This field is required when resource.type is model."
        ),
    ] = None
    key_name: Annotated[
        str | None,
        Field(
            description="Credential label from the gateway registry. It MUST contain no key material, prefix, hash, or other secret substring.",
            examples=["prod-shared", "team-research", "byo-acme"],
        ),
    ] = None
    region: Annotated[
        str | None,
        Field(
            description="Region affecting price and data residency.",
            examples=["us-east-1", "eu-central-1"],
        ),
    ] = None
    deployment: Annotated[
        str | None,
        Field(
            description="Open-vocabulary deployment platform or environment, such as AWS, GCP, Azure, or self-hosted.",
            examples=["AWS", "GCP", "Azure", "self-hosted"],
            min_length=1,
        ),
    ] = None


class Run(FrozenBase):
    """
    Groups metered operations into a task and span hierarchy. Spawned agents reuse run_id, parent_span_id links within that run, and a harness outcome closes the run.
    """

    run_id: Annotated[
        str,
        Field(
            description="Unique run identifier, generated by the harness or by the router when no harness exists. It MUST be account-unique and identical on every record in the run, including spawned-agent records.",
            max_length=64,
            min_length=8,
        ),
    ]
    name: Annotated[
        str | None,
        Field(
            description="Optional human-readable name of the agentic run. When absent, run_id is used in its place for display purposes.",
            min_length=1,
        ),
    ] = None
    span_id: Annotated[
        str,
        Field(
            description="Span identifier for one metered operation, unique within run_id. Together they form the sink merge key, which MUST NOT be shared by different operations.",
            min_length=1,
        ),
    ]
    parent_span_id: Annotated[
        str | None,
        Field(
            description="Links nested tools and spawned agents to a span in the same run_id. Spawned agents MUST reuse the parent run_id and set this field to their spawning span.",
            min_length=1,
        ),
    ] = None
    step: Annotated[
        int | None, Field(description="Ordinal position within the run.", ge=0)
    ] = None
    trace_id: Annotated[
        str | None,
        Field(description="W3C trace identifier for OpenTelemetry correlation."),
    ] = None
    run_type: Annotated[
        Literal["agent_run", "workflow", "single_call"] | None,
        Field(description="Overall work shape."),
    ] = None
    error_code: Annotated[
        str | None,
        Field(
            description="Error code when the run fails. Report consumed usage even on failure; downstream rating decides billability.",
            examples=[
                "TOOL_TIMEOUT",
                "PROVIDER_5XX",
                "CONTENT_POLICY_VIOLATION",
                "CAPACITY_UNAVAILABLE",
                "SERVICE_UNAVAILABLE",
                "CLIENT_CANCELLED",
            ],
            min_length=1,
        ),
    ] = None
    error_reason: Annotated[
        str | None,
        Field(
            description="Human-readable message of the run failure, limited to 32 characters.",
            examples=["sandbox wall-clock exceeded"],
            max_length=32,
        ),
    ] = None
    outcome: Annotated[
        Literal["resolved", "escalated", "abandoned", "failed"] | None,
        Field(
            description="The agent run's final outcome, emitted only by the harness."
        ),
    ] = None


LabelsAdditionalProperty = TypeAliasType(
    "LabelsAdditionalProperty", Annotated[str, Field(max_length=256)]
)


class Attribution(FrozenBase):
    """
    Carries billability and allocation dimensions. Emitters MUST supply environment; sinks ignore records missing it, and production records require account_id.
    """

    environment: Annotated[
        Literal["production", "staging", "development", "test", "evaluation"] | None,
        Field(
            description="Deployment environment. A conformant emitter MUST populate it; a missing value triggers default-deny ignore."
        ),
    ] = None
    user_id: Annotated[
        str | None,
        Field(
            description="Pseudonymous identity of the triggering user; never an email or name. It MUST NOT be used by rating; account_id MUST be used for rating."
        ),
    ] = None
    account_id: Annotated[
        str | None,
        Field(
            description="The account that pays the bill. Rating may aggregate usage by this account. Required for production traffic; optional otherwise.",
            min_length=1,
        ),
    ] = None
    subscription_id: Annotated[
        str | None,
        Field(
            description="Subscription associated with the paying account for this usage record."
        ),
    ] = None
    labels: Annotated[
        dict[
            constr(pattern=r"^[a-zA-Z0-9_.-]+$", max_length=64),
            LabelsAdditionalProperty,
        ]
        | None,
        Field(
            description="Up to 20 free-form dimensions for non-billable metadata. Labels MUST NOT contain PII.",
            max_length=20,
        ),
    ] = None


class LlmUsage(ExtensibleBase):
    """
    Non-empty model-call counters. A harness may emit counters read from the provider response.
    """

    input_tokens: Annotated[
        int | None,
        Field(description="Uncached input tokens; MUST exclude cache reads.", ge=0),
    ] = None
    output_tokens: Annotated[
        int | None,
        Field(
            description="Output tokens; exclude reasoning tokens when reasoning_tokens is present.",
            ge=0,
        ),
    ] = None
    cache_read_tokens: Annotated[
        int | None,
        Field(
            description="Prompt-cache read tokens, reported separately for distinct pricing.",
            ge=0,
        ),
    ] = None
    cache_write_tokens: Annotated[
        int | None,
        Field(description="Tokens written to a prompt cache by this call.", ge=0),
    ] = None
    reasoning_tokens: Annotated[
        int | None,
        Field(
            description="Reasoning tokens, separate from output for independent pricing.",
            ge=0,
        ),
    ] = None
    requests: Annotated[
        int | None,
        Field(
            description="Request count for per-request pricing. No default applies: absent means unreported, while one request is encoded as 1.",
            ge=0,
        ),
    ] = None
    images_processed: Annotated[
        int | None, Field(description="Images supplied in model input.", ge=0)
    ] = None
    audio_input_seconds: Annotated[
        float | None, Field(description="Seconds of audio submitted.", ge=0.0)
    ] = None
    audio_output_seconds: Annotated[
        float | None, Field(description="Seconds of audio generated.", ge=0.0)
    ] = None


class ToolUsage(ExtensibleBase):
    """
    Non-empty counters reported by the component that executed the tool: harness for caller-held contracts, router for provider-executed tools.
    """

    type: Annotated[
        str | None,
        Field(
            description="The tool operation being metered, such as invocation, api, web_search, code_execution, or retrieval. It complements resource.operation and resource.name.",
            min_length=1,
        ),
    ] = None
    call_count: Annotated[
        int | None,
        Field(
            description="Invocation or run count used for per-call pricing. For retrieval, this is usually the query count.",
            ge=0,
        ),
    ] = None
    sandbox_time: Annotated[
        float | None,
        Field(
            description="Sandbox compute wall-clock time in milliseconds, distinct from whole-operation timing.duration_ms. Used when an agent run spins up a sandbox for tool execution.",
            ge=0.0,
        ),
    ] = None


class Usage(FrozenBase):
    """
    Raw, non-monetary counters with exactly one non-empty llm or tool block selected by resource.operation. An absent counter means unreported or inapplicable; zero means measured as zero and MUST NOT be inferred from absence.
    """

    llm: Annotated[
        LlmUsage | None,
        Field(
            description="Non-empty model-call counters. A harness may emit counters read from the provider response.",
            title="LlmUsage",
        ),
    ] = None
    tool: Annotated[
        ToolUsage | None,
        Field(
            description="Non-empty counters reported by the component that executed the tool: harness for caller-held contracts, router for provider-executed tools.",
            title="ToolUsage",
        ),
    ] = None


class LlmCost(FrozenBase):
    """
    The gross cost of the model operation calls. The breakdown is similar to usage.llm and is present only for model operations.
    """

    total_token_cost: Annotated[
        float,
        Field(
            description="Total token cost for this model call event. Reference only and MAY have rounding differences with the sum of individual token costs.",
            ge=0.0,
        ),
    ]
    input_token_cost: Annotated[
        float | None,
        Field(
            description="Cost of uncached input tokens. This would be the total input token cost if cache_read_cost were absent.",
            ge=0.0,
        ),
    ] = None
    output_token_cost: Annotated[
        float | None,
        Field(description="Output token cost and MUST exclude reasoning_cost.", ge=0.0),
    ] = None
    cache_read_cost: Annotated[
        float | None, Field(description="Prompt-cache read cost.", ge=0.0)
    ] = None
    cache_write_cost: Annotated[
        float | None, Field(description="Prompt-cache write cost.", ge=0.0)
    ] = None
    reasoning_cost: Annotated[
        float | None, Field(description="Reasoning-token cost.", ge=0.0)
    ] = None


class ToolCost(ExtensibleBase):
    """
    The gross cost of the tool execution calls. The breakdown is similar to usage.tool and is present only for tool_execution and retrieval.
    """

    type: Annotated[
        str | None,
        Field(
            description="The tool operation being metered. It SHOULD match usage.tool.type on the same record.",
            min_length=1,
        ),
    ] = None
    call_cost: Annotated[
        float | None,
        Field(
            description="Per-invocation charge corresponding to usage.tool.call_count.",
            ge=0.0,
        ),
    ] = None
    sandbox_cost: Annotated[
        float | None,
        Field(description="Charge corresponding to usage.tool.sandbox_time.", ge=0.0),
    ] = None


class Cost(FrozenBase):
    """
    Provider- or router-asserted cost that rating MAY use or ignore according to its billing configuration. Components are gross, total_cost is net, and the single cost sub-block must match usage; rating MAY check consistency but MUST NOT overwrite the total.
    """

    total_cost: Annotated[
        float, Field(description="Event-level total cost after discounts.", ge=0.0)
    ]
    currency: Annotated[
        str,
        Field(
            description="Currency code of the costs in uppercase according to ISO 4217 format.",
            pattern="^[A-Z]{3}$",
        ),
    ]
    llm: Annotated[
        LlmCost | None,
        Field(
            description="The gross cost of the model operation calls. The breakdown is similar to usage.llm and is present only for model operations.",
            title="LlmCost",
        ),
    ] = None
    tool: Annotated[
        ToolCost | None,
        Field(
            description="The gross cost of the tool execution calls. The breakdown is similar to usage.tool and is present only for tool_execution and retrieval.",
            title="ToolCost",
        ),
    ] = None
    original_cost: Annotated[
        float | None,
        Field(
            description="List cost before commitments, negotiated rates, or promotions.",
            ge=0.0,
        ),
    ] = None
    discount_amount: Annotated[
        float | None,
        Field(description="Difference between original_cost and total_cost.", ge=0.0),
    ] = None
    discount_percent: Annotated[
        float | None,
        Field(
            description="Any provider promotional discount percentage.",
            ge=0.0,
            le=100.0,
        ),
    ] = None


class AUDR(FrozenBase):
    """
    This specification defines the Agent Usage Detail Record (AUDR), a JSON object that describes one metered operation in an agent system. A record identifies its emitter and resource, reports raw model or tool usage, associates the operation with a run, and carries attribution required for downstream cost allocation. A record MAY include an informational cost assertion.
    """

    spec_version: Annotated[
        str,
        Field(
            description="AUDR schema version, constrained here to 1.0.x. Consumers MUST reject unsupported major versions.",
            examples=["1.0.0"],
            pattern="^1\\.0\\.\\d+$",
        ),
    ]
    record_id: Annotated[
        str,
        Field(
            description="ULID or UUIDv7 idempotency key, unique to each emitted record rather than each logical event. Records from different components use distinct IDs and are merged, not deduplicated.",
            max_length=64,
            min_length=8,
        ),
    ]
    emitter: Annotated[
        Emitter,
        Field(
            description="Identifies the software component that wrote the record.",
            title="Emitter",
        ),
    ]
    corrects: Annotated[
        str | None,
        Field(
            description="Identifies one earlier record fully restated by this correction. The correction MUST contain full state, use a fresh record_id, and come from the same emitter.component; all-zero usage represents a void.",
            max_length=64,
            min_length=8,
        ),
    ] = None
    timing: Annotated[
        Timing,
        Field(
            description="Event completion, ingest, and duration observations.",
            title="Timing",
        ),
    ]
    resource: Annotated[
        Resource,
        Field(
            description="Identifies the consumed model or tool. Model operations require type=model; tool_execution and retrieval require type=tool.",
            title="Resource",
        ),
    ]
    run: Annotated[
        Run,
        Field(
            description="Groups metered operations into a task and span hierarchy. Spawned agents reuse run_id, parent_span_id links within that run, and a harness outcome closes the run.",
            title="Run",
        ),
    ]
    attribution: Annotated[
        Attribution,
        Field(
            description="Carries billability and allocation dimensions. Emitters MUST supply environment; sinks ignore records missing it, and production records require account_id.",
            title="Attribution",
        ),
    ]
    usage: Annotated[
        Usage,
        Field(
            description="Raw, non-monetary counters with exactly one non-empty llm or tool block selected by resource.operation. An absent counter means unreported or inapplicable; zero means measured as zero and MUST NOT be inferred from absence.",
            title="Usage",
        ),
    ]
    cost: Annotated[
        Cost | None,
        Field(
            description="Provider- or router-asserted cost that rating MAY use or ignore according to its billing configuration. Components are gross, total_cost is net, and the single cost sub-block must match usage; rating MAY check consistency but MUST NOT overwrite the total.",
            title="Cost",
        ),
    ] = None
