"""The audr public API: build, validate, and deliver AUDR usage records."""

from audr._version import __version__
from audr.client import Client
from audr.errors import (
    AudrError,
    ConfigurationError,
    LifecycleError,
    ValidationError,
    ValidationIssue,
)
from audr.record import (
    AUDR,
    SPEC_VERSION,
    Attribution,
    Cost,
    Emitter,
    EmitterComponent,
    Environment,
    ErrorCode,
    LlmCost,
    LlmUsage,
    Modality,
    Operation,
    Resource,
    ResourceType,
    Run,
    RunOutcome,
    RunType,
    Timing,
    ToolCost,
    ToolUsage,
    Usage,
)
from audr.results import (
    DeliveredCallback,
    DeliveryStats,
    Disposition,
    FailedRecord,
    FailureCallback,
    FailureReason,
    SubmitOutcome,
    SubmitResult,
)
from audr.sinks import BatchOutcome, BatchResult, FileFormat, FileSink, RejectedRecord, Sink

__all__ = [
    "AUDR",
    "SPEC_VERSION",
    "Attribution",
    "AudrError",
    "BatchOutcome",
    "BatchResult",
    "Client",
    "ConfigurationError",
    "Cost",
    "DeliveredCallback",
    "DeliveryStats",
    "Disposition",
    "Emitter",
    "EmitterComponent",
    "Environment",
    "ErrorCode",
    "FailedRecord",
    "FailureCallback",
    "FailureReason",
    "FileFormat",
    "FileSink",
    "LifecycleError",
    "LlmCost",
    "LlmUsage",
    "Modality",
    "Operation",
    "RejectedRecord",
    "Resource",
    "ResourceType",
    "Run",
    "RunOutcome",
    "RunType",
    "Sink",
    "SubmitOutcome",
    "SubmitResult",
    "Timing",
    "ToolCost",
    "ToolUsage",
    "Usage",
    "ValidationError",
    "ValidationIssue",
    "__version__",
]
