// GENERATED by scripts/gen-schema.ts from spec/audr.schema.json. DO NOT EDIT.

/** The AUDR release this package implements, from the schema's `$id`. */
export const SPEC_VERSION = '1.0.0';
/** Every `spec_version` the schema admits. */
export const SUPPORTED_SPEC_VERSION = /^1\.0\.\d+$/;

/** An `x_*` provider or implementation counter. */
export type ExtensionKey = `x_${string}`;

/**
 * This specification defines the Agent Usage Detail Record (AUDR), a JSON object that
 * describes one metered operation in an agent system. A record identifies its emitter and
 * resource, reports raw model or tool usage, associates the operation with a run, and
 * carries attribution required for downstream cost allocation. A record MAY include an
 * informational cost assertion.
 */
export interface AudrRecordShape {
  /**
   * Carries billability and allocation dimensions. Emitters MUST supply environment; sinks
   * ignore records missing it, and production records require account_id.
   */
  readonly attribution: Attribution;
  /**
   * Identifies one earlier record fully restated by this correction. The correction MUST
   * contain full state, use a fresh record_id, and come from the same emitter.component;
   * all-zero usage represents a void.
   */
  readonly corrects?: string | undefined;
  /**
   * Provider- or router-asserted cost that rating MAY use or ignore according to its billing
   * configuration. Components are gross, total_cost is net, and the single cost sub-block
   * must match usage; rating MAY check consistency but MUST NOT overwrite the total.
   */
  readonly cost?: Cost | undefined;
  /**
   * Identifies the software component that wrote the record.
   */
  readonly emitter: Emitter;
  /**
   * ULID or UUIDv7 idempotency key, unique to each emitted record rather than each logical
   * event. Records from different components use distinct IDs and are merged, not
   * deduplicated.
   */
  readonly record_id: string;
  /**
   * Identifies the consumed model or tool. Model operations require type=model;
   * tool_execution and retrieval require type=tool.
   */
  readonly resource: Resource;
  /**
   * Groups metered operations into a task and span hierarchy. Spawned agents reuse run_id,
   * parent_span_id links within that run, and a harness outcome closes the run.
   */
  readonly run: Run;
  /**
   * AUDR schema version, constrained here to 1.0.x. Consumers MUST reject unsupported major
   * versions.
   */
  readonly spec_version: string;
  /**
   * Event completion, ingest, and duration observations.
   */
  readonly timing: Timing;
  /**
   * Raw, non-monetary counters with exactly one non-empty llm or tool block selected by
   * resource.operation. An absent counter means unreported or inapplicable; zero means
   * measured as zero and MUST NOT be inferred from absence.
   */
  readonly usage: Usage;
}

/**
 * Carries billability and allocation dimensions. Emitters MUST supply environment; sinks
 * ignore records missing it, and production records require account_id.
 */
export interface Attribution {
  /**
   * The account that pays the bill. Rating may aggregate usage by this account. Required for
   * production traffic; optional otherwise.
   */
  readonly account_id?: string | undefined;
  /**
   * Deployment environment. A conformant emitter MUST populate it; a missing value triggers
   * default-deny ignore.
   */
  readonly environment?: Environment | undefined;
  /**
   * Up to 20 free-form dimensions for non-billable metadata. Labels MUST NOT contain PII.
   */
  readonly labels?: Readonly<Record<string, string>> | undefined;
  /**
   * Subscription associated with the paying account for this usage record.
   */
  readonly subscription_id?: string | undefined;
  /**
   * Pseudonymous identity of the triggering user; never an email or name. It MUST NOT be used
   * by rating; account_id MUST be used for rating.
   */
  readonly user_id?: string | undefined;
}

/**
 * Deployment environment. A conformant emitter MUST populate it; a missing value triggers
 * default-deny ignore.
 */
export type Environment = 'production' | 'staging' | 'development' | 'test' | 'evaluation';

/**
 * Provider- or router-asserted cost that rating MAY use or ignore according to its billing
 * configuration. Components are gross, total_cost is net, and the single cost sub-block
 * must match usage; rating MAY check consistency but MUST NOT overwrite the total.
 */
export interface Cost {
  /**
   * Currency code of the costs in uppercase according to ISO 4217 format.
   */
  readonly currency: string;
  /**
   * Difference between original_cost and total_cost.
   */
  readonly discount_amount?: number | undefined;
  /**
   * Any provider promotional discount percentage.
   */
  readonly discount_percent?: number | undefined;
  /**
   * The gross cost of the model operation calls. The breakdown is similar to usage.llm and is
   * present only for model operations.
   */
  readonly llm?: LlmCost | undefined;
  /**
   * List cost before commitments, negotiated rates, or promotions.
   */
  readonly original_cost?: number | undefined;
  /**
   * The gross cost of the tool execution calls. The breakdown is similar to usage.tool and is
   * present only for tool_execution and retrieval.
   */
  readonly tool?: ToolCost | undefined;
  /**
   * Event-level total cost after discounts.
   */
  readonly total_cost: number;
}

/**
 * The gross cost of the model operation calls. The breakdown is similar to usage.llm and is
 * present only for model operations.
 */
export interface LlmCost {
  /**
   * Prompt-cache read cost.
   */
  readonly cache_read_cost?: number | undefined;
  /**
   * Prompt-cache write cost.
   */
  readonly cache_write_cost?: number | undefined;
  /**
   * Cost of uncached input tokens. This would be the total input token cost if
   * cache_read_cost were absent.
   */
  readonly input_token_cost?: number | undefined;
  /**
   * Output token cost and MUST exclude reasoning_cost.
   */
  readonly output_token_cost?: number | undefined;
  /**
   * Reasoning-token cost.
   */
  readonly reasoning_cost?: number | undefined;
  /**
   * Total token cost for this model call event. Reference only and MAY have rounding
   * differences with the sum of individual token costs.
   */
  readonly total_token_cost: number;
}

/**
 * The gross cost of the tool execution calls. The breakdown is similar to usage.tool and is
 * present only for tool_execution and retrieval.
 */
export interface ToolCost {
  /**
   * Per-invocation charge corresponding to usage.tool.call_count.
   */
  readonly call_cost?: number | undefined;
  /**
   * Charge corresponding to usage.tool.sandbox_time.
   */
  readonly sandbox_cost?: number | undefined;
  /**
   * The tool operation being metered. It SHOULD match usage.tool.type on the same record.
   */
  readonly type?: string | undefined;
  /** Charge amount for an implementation-specific field named x_<name>. */
  readonly [key: ExtensionKey]: number | undefined;
}

/**
 * Identifies the software component that wrote the record.
 */
export interface Emitter {
  /**
   * Component that wrote the record. This field identifies the caller that metered tool usage
   * and cost.
   */
  readonly component: EmitterComponent;
  /**
   * Package identifier for the emitter.
   */
  readonly name: string;
  /**
   * Emitter release used to attribute data-quality issues.
   */
  readonly version: string;
}

/**
 * Component that wrote the record. This field identifies the caller that metered tool usage
 * and cost.
 */
export type EmitterComponent = 'harness' | 'router' | 'provider';

/**
 * Identifies the consumed model or tool. Model operations require type=model;
 * tool_execution and retrieval require type=tool.
 */
export interface Resource {
  /**
   * Open-vocabulary deployment platform or environment, such as AWS, GCP, Azure, or
   * self-hosted.
   */
  readonly deployment?: string | undefined;
  /**
   * Credential label from the gateway registry. It MUST contain no key material, prefix,
   * hash, or other secret substring.
   */
  readonly key_name?: string | undefined;
  /**
   * The modality of the task or operation. This field is required when resource.type is model.
   */
  readonly modality?: Modality | undefined;
  /**
   * Verbatim provider model identifier for models, or stable logical tool/backend identifier
   * for tools. Do not normalize model names or use URLs and versioned function symbols for
   * tools.
   */
  readonly name: string;
  /**
   * Operation class that selects resource.type and usage: model operations use model with
   * usage.llm; tool_execution and retrieval use tool with usage.tool.
   */
  readonly operation: Operation;
  /**
   * Canonical lowercase provider slug. For tool operations, identify the executing vendor or
   * platform; use self-hosted for locally run tools.
   */
  readonly provider: string;
  /**
   * Region affecting price and data residency.
   */
  readonly region?: string | undefined;
  /**
   * Named resource kind: model for model operations or tool for tool_execution and retrieval.
   * resource.operation selects the usage block.
   */
  readonly type: ResourceType;
}

/**
 * The modality of the task or operation. This field is required when resource.type is model.
 */
export type Modality = 'text' | 'image' | 'audio' | 'multimodal';

/**
 * Operation class that selects resource.type and usage: model operations use model with
 * usage.llm; tool_execution and retrieval use tool with usage.tool.
 */
export type Operation = 'generation' | 'embedding' | 'reranking' | 'tool_execution' | 'retrieval';

/**
 * Named resource kind: model for model operations or tool for tool_execution and retrieval.
 * resource.operation selects the usage block.
 */
export type ResourceType = 'model' | 'tool';

/**
 * Groups metered operations into a task and span hierarchy. Spawned agents reuse run_id,
 * parent_span_id links within that run, and a harness outcome closes the run.
 */
export interface Run {
  /**
   * Error code when the run fails. Report consumed usage even on failure; downstream rating
   * decides billability.
   */
  readonly error_code?: string | undefined;
  /**
   * Human-readable message of the run failure, limited to 32 characters.
   */
  readonly error_reason?: string | undefined;
  /**
   * Optional human-readable name of the agentic run. When absent, run_id is used in its place
   * for display purposes.
   */
  readonly name?: string | undefined;
  /**
   * The agent run's final outcome, emitted only by the harness.
   */
  readonly outcome?: RunOutcome | undefined;
  /**
   * Links nested tools and spawned agents to a span in the same run_id. Spawned agents MUST
   * reuse the parent run_id and set this field to their spawning span.
   */
  readonly parent_span_id?: string | undefined;
  /**
   * Unique run identifier, generated by the harness or by the router when no harness exists.
   * It MUST be account-unique and identical on every record in the run, including
   * spawned-agent records.
   */
  readonly run_id: string;
  /**
   * Overall work shape.
   */
  readonly run_type?: RunType | undefined;
  /**
   * Span identifier for one metered operation, unique within run_id. Together they form the
   * sink merge key, which MUST NOT be shared by different operations.
   */
  readonly span_id: string;
  /**
   * Ordinal position within the run.
   */
  readonly step?: number | undefined;
  /**
   * W3C trace identifier for OpenTelemetry correlation.
   */
  readonly trace_id?: string | undefined;
}

/**
 * The agent run's final outcome, emitted only by the harness.
 */
export type RunOutcome = 'resolved' | 'escalated' | 'abandoned' | 'failed';

/**
 * Overall work shape.
 */
export type RunType = 'agent_run' | 'workflow' | 'single_call';

/**
 * Event completion, ingest, and duration observations.
 */
export interface Timing {
  /**
   * Event execution duration in milliseconds.
   */
  readonly duration_ms?: number | undefined;
  /**
   * Event invocation time in RFC 3339 format with millisecond precision; for streams, use
   * stream termination.
   */
  readonly event_time: string;
  /**
   * Ingest time in RFC 3339 format with millisecond precision. Set by the sink.
   */
  readonly received_time?: string | undefined;
}

/**
 * Raw, non-monetary counters with exactly one non-empty llm or tool block selected by
 * resource.operation. An absent counter means unreported or inapplicable; zero means
 * measured as zero and MUST NOT be inferred from absence.
 */
export interface Usage {
  /**
   * Non-empty model-call counters. A harness may emit counters read from the provider
   * response.
   */
  readonly llm?: LlmUsage | undefined;
  /**
   * Non-empty counters reported by the component that executed the tool: harness for
   * caller-held contracts, router for provider-executed tools.
   */
  readonly tool?: ToolUsage | undefined;
}

/**
 * Non-empty model-call counters. A harness may emit counters read from the provider
 * response.
 */
export interface LlmUsage {
  /**
   * Seconds of audio submitted.
   */
  readonly audio_input_seconds?: number | undefined;
  /**
   * Seconds of audio generated.
   */
  readonly audio_output_seconds?: number | undefined;
  /**
   * Prompt-cache read tokens, reported separately for distinct pricing.
   */
  readonly cache_read_tokens?: number | undefined;
  /**
   * Tokens written to a prompt cache by this call.
   */
  readonly cache_write_tokens?: number | undefined;
  /**
   * Images supplied in model input.
   */
  readonly images_processed?: number | undefined;
  /**
   * Uncached input tokens; MUST exclude cache reads.
   */
  readonly input_tokens?: number | undefined;
  /**
   * Output tokens; exclude reasoning tokens when reasoning_tokens is present.
   */
  readonly output_tokens?: number | undefined;
  /**
   * Reasoning tokens, separate from output for independent pricing.
   */
  readonly reasoning_tokens?: number | undefined;
  /**
   * Request count for per-request pricing. No default applies: absent means unreported, while
   * one request is encoded as 1.
   */
  readonly requests?: number | undefined;
  /** Non-negative provider counter named x_<provider>_<name>. */
  readonly [key: ExtensionKey]: number | undefined;
}

/**
 * Non-empty counters reported by the component that executed the tool: harness for
 * caller-held contracts, router for provider-executed tools.
 */
export interface ToolUsage {
  /**
   * Invocation or run count used for per-call pricing. For retrieval, this is usually the
   * query count.
   */
  readonly call_count?: number | undefined;
  /**
   * Sandbox compute wall-clock time in milliseconds, distinct from whole-operation
   * timing.duration_ms. Used when an agent run spins up a sandbox for tool execution.
   */
  readonly sandbox_time?: number | undefined;
  /**
   * The tool operation being metered, such as invocation, api, web_search, code_execution, or
   * retrieval. It complements resource.operation and resource.name.
   */
  readonly type?: string | undefined;
  /** Non-negative implementation counter named x_<name>. */
  readonly [key: ExtensionKey]: number | undefined;
}
